spring:
  application:
    name: ai-interview-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ai_interviewer}
    username: ${DB_USERNAME:ai}
    password: ${DB_PASSWORD:ai}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      project-id: ${OPENAI_API_PROJECT_ID:}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-5-chat-latest}
          temperature: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.ai.chat.client.advisor: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
